### ISSUE TITLE
Create a container that will create a CR to be used by pulp-operator 

### ISSUE THREAD

**Issue by dkliban** [pulp/pulp-clowder-deployments#1]
The behavior of `pulp-operator` is defined with a Custom Resource (CR). The CR for the deployment with Clowder will need to specify at least two Kubernetes secrets: `external_cache_secret` and `external_db_secret`. These secrets will be generated from data provided in the Clowder config that is passed into a container using `ACG_CONFIG` environment variable. `app-common-python` package[0] provides the ability to easily consume this config. 

A new container image needs to be created to perform the following tasks:

1. Create the `external_cache_secret` from the `inMemoryDb` config in the `ACG_CONFIG` environment variable.
2. Create the `external_db_secret` from the `database` config in the `ACG_CONFIG` environment variable.
3. Create a CR that includes the proper values for `external_cache_secret`  and `external_db_secret`. 

The container should be able to just run a simple script that does this in Python. Though I am open to this being written in Go. There is a Go library also[1].

This container will run in parallel with the `pulp-operator` container. It will remain running only for as long as it takes to perform the above operations. `pulp-operator` will do all of its work once the CR is created.  

[0] https://github.com/RedHatInsights/app-common-python
[1] https://github.com/RedHatInsights/app-common-go

**Comment by git-hyagi** [comment]
If we are going to use object storage this container would also need to generate the `Secret` (and the custom Pulp settings)  with it, right?

**Comment by dkliban** [comment]
Yes, we will need to create a secret for the object storage. It's provided in `ACG_CONFIG` as `objectStore'[0].

[0] https://github.com/RedHatInsights/app-common-python/blob/master/test.json#L42-L56
