### ISSUE TITLE
ephemeral deployments don't seem to have the correct content_origin

### ISSUE THREAD

**Issue by jlsherrill** [pulp/pulp-clowder-deployments#94]
When deploying an ephemeral environment the content_origin is not correct and is referencing the internal pod name:

"content_settings":{"content_origin":"http://cs-pulp-content-svc.local","content_path_prefix":"/pulp/content/"}

**Comment by dkliban** [comment]
There must be a race condition. I will add some retry logic on setting the content_origin.
